<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-1S7KVVBR" failures="0" tests="1" name="pages.Testcase4" time="0.527" errors="1" timestamp="2024-05-30T22:06:58 IST" skipped="0">
  <testcase classname="pages.Testcase4" name="Testcase04" time="0.527">
    <error message="
[public void pages.Testcase4.Testcase04(java.lang.String,java.lang.String,java.lang.String[],java.lang.String[],java.lang.String[]) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: Testcase04([java.lang.String arg0, java.lang.String arg1, java.lang.String[] arg2, java.lang.String[] arg3, java.lang.String[] arg4])
Arguments: [(java.lang.String) 62c91926-1aa8-43f9-8449-0b232de708f6_1,(java.lang.String) TC4_1@gmail.com,(java.lang.String) abc@123,(java.lang.String) Bengaluru;Niaboytown;Chicky;01-01-2025;2,(java.lang.String) Kolkata;Thton;Cha Cha;01-02-2025;3,(java.lang.String) Malaysia;Wootkentree;Bom Bom;02-12-2025;1]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void pages.Testcase4.Testcase04(java.lang.String,java.lang.String,java.lang.String[],java.lang.String[],java.lang.String[]) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: Testcase04([java.lang.String arg0, java.lang.String arg1, java.lang.String[] arg2, java.lang.String[] arg3, java.lang.String[] arg4])
Arguments: [(java.lang.String) 62c91926-1aa8-43f9-8449-0b232de708f6_1,(java.lang.String) TC4_1@gmail.com,(java.lang.String) abc@123,(java.lang.String) Bengaluru;Niaboytown;Chicky;01-01-2025;2,(java.lang.String) Kolkata;Thton;Cha Cha;01-02-2025;3,(java.lang.String) Malaysia;Wootkentree;Bom Bom;02-12-2025;1]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Testcase04 -->
</testsuite> <!-- pages.Testcase4 -->
